chat_app/config/routes.rb
Rails.application.routes.draw do

  resources :groups, only: [:index, :create, :show]do
    resources :messages, only: [ :create, :index]do
    
    end
  end

  # resources :groups
  resources :messages, only: [:index, :create]do
    collection do
      get 'index/:user_id', :action => 'index'
    end
  end

  
  resources :sessions, only: [:new, :create] do
    resources :groups, only: [:index, :create ]do
      resources :messages, only: [ :create]do
        collection do
          get 'index/:user_id', :action => 'index'
        end
      end
    end
  end

  root 'sessions#new'
  match "sessions/delete_cookies" => "sessions#delete_cookies", :via => :delete

end

chat_app/app/models/group.rb
class Group < ActiveRecord::Base
	has_many :messages
	
end

chat_app/app/models/message.rb
class Message < ActiveRecord::Base
	#belongs_to :user
	belongs_to :group
end

chat_app/app/models/session.rb
class Session < ActiveRecord::Base
end

chat_app/app/models/user.rb
class User < ActiveRecord::Base
  #has_many :messages
  has_many :groups
end

chat_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
end

chat_app/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
     redirect_to  group_messages_path(@group)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_params
      params[:group]
    end
end

chat_app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @user = User.find(cookies.signed[:user_id])
    
  end

  def create
    group = Group.find(params[:message][:group_id])
    # @message = Message.create(message: params[:message][:body],group_name: params[:format])

    ActionCable.server.broadcast "messages_#{group.name}",
      message: params[:message][:body],
      username: cookies.signed[:username],
      groupname: group.name

    head :ok
  end

end

chat_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    current_user = (params[:session][:username])
    cookies.signed[:username] = params[:session][:username]
    @user = User.create(name: params[:session][:username])
    cookies.signed[:user_id] = @user.id
    #redirect_to messages_path(@user.id)
    redirect_to groups_path
  end

  def show_cookies
    @user_name = cookies[:username]
  end

  def delete_cookies
    cookies.signed[:username] = nil
    @user = User.find(params[:id])
    @user.destroy
  end

end

chat_app/app/helpers/application_helper.rb
module ApplicationHelper
end

chat_app/app/helpers/groups_helper.rb
module GroupsHelper
end

chat_app/app/helpers/messages_helper.rb
module MessagesHelper
end

chat_app/app/helpers/places_helper.rb
module PlacesHelper
end

chat_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

chat_app/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

chat_app/app/views/groups/_group.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
      <div class="group_new">
       <%= text_field_tag(:name ,nil, class: "group_new") %>
       </div>
    </tr>
  </thead>
 <div class = "list_groups">
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </div>
</table>

<br>

chat_app/app/views/groups/create.js.erb
$(".list_groups").empty().append("<%= escape_javascript(render(:partial => 'group', locale: {groups: @groups}, layout: false ).html_safe) %>")

chat_app/app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

chat_app/app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <h4><%= link_to group.name, group %></h4>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br/><br/>
<% @client = GooglePlaces::Client.new("AIzaSyD2koU2SoZWJ6N4ay0oirdHnEpz7Wm4bxI") %>

spots_by_radar

<%  @c = @client.spots_by_radar(10.008935,76.3506809, :name => 'kochi' ) %>
<% @c.each do |client|
%>
<%= client.lat  %> <br>
<% end %>

<br><br>

spots
<% @clients = @client.spots(10.008935,76.3506809, :query => 'kochi' )

@clients.each do |client|
%>
<%= client.name %> <br>
<% end %>
 <%

@client = GooglePlaces::Client.new("AIzaSyD2koU2SoZWJ6N4ay0oirdHnEpz7Wm4bxI")
@output = @client.predictions_by_input(
    'San F',
    lat: 0.0,
    lng: 0.0,
    radius: 20000000,
    types: 'geocode',
    language: I18n.locale,
)

%>
-----------------------------------------------------------------------------------------------------------------------
<% @output.each do |output|%>
<%= output.description  %>
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
<% end %>
---------------------------------------------------------------------------------------------------------------------------
 <br><br>
 request
 <% @r = GooglePlaces::Request::NEARBY_SEARCH_URL  %>
 <%= @r %> 

chat_app/app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

chat_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

chat_app/app/views/messages/index.html.erb
Signed in as @<%= @user.name %>.


<div id='messages'> <br></div>

<br/><br/>

<%= form_for :message, url:   group_messages_path , remote: true, id: 'messages-form' do |f| %>
  <%= f.label :body, 'Enter a message:'  %><br/>
  <%= f.text_field :body %><br/>

<%= f.hidden_field :user_id, :value => "#{@user.id}" %>
<%= f.hidden_field :group_id, :value => "#{@group.id}" %>

<div class ="m" value ="messages_<%= @group.name%>" >
  <%= f.submit 'Send message' , :id => 'm', :class => 'm', :value =>"messages_#{@group.name}" %>
  </div>
<% end %>

<!--body onbeforeunload="deleteAllCookies()"-->

<script type="text/javascript">

var delete_cookie = function(name) {
    document.cookie = name + '=;expires=Thu, 01 Jan 1970 00:00:01 GMT;';
};

function deleteAllCookies() {
$.ajax({
       method: 'delete',
       url:'/sessions/delete_cookies',
       cache: false,
       data: {id: <%= @user.id %>},
       success: function(html){
       alert("success");
       }
      });

   delete_cookie('username');
}


</script>